project_id = "cnrznkphuuykehwkpfgy"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://cnrznkphuuykehwkpfgy.supabase.co"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[edge_runtime]
enabled = true
port = 54325

[functions.ai-chat]
verify_jwt = false

[functions.crop-prediction]
verify_jwt = false

[functions.yield-prediction]
verify_jwt = false

[functions.market-recommendations]
verify_jwt = false