// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnrznkphuuykehwkpfgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucnpua3BodXV5a2Vod2twZmd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3Mzg2MTIsImV4cCI6MjA3NDMxNDYxMn0.5zOlcrJsrs5EuMP8C8j-ZGFL2Dx0HF0dVvde6OGm-hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});